version: '3'

services:
  app1:
   image: http_api
   ports:
     - 4001:4000
  app2:
   image: http_api
   ports:
     - 4002:4000
  app3:
   image: http_api
   ports:
     - 4003:4000

  haproxy:
    image: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - 4000:80
