defmodule HttpApi.Protobuf do
  @moduledoc """
  Module to hold the structs generated by exprotobuf.
  """

  # Generates encoders, decoders and struct definitions from protobuf schemas.
  use Protobuf, from: Application.app_dir(:http_api, "priv/football_results.proto")
end
